---
# Base de datos local: 1
# Base de datos externa: 2
identify: 1
...
---
# Para base de datos interna o local: 1
type: 'mysql'
server: 'localhost'
port: '3306'
user: 'root'
password: '12345678'
database: 'vitriappcombd'
...

---
# Para base de datos externa o la del hosting: 2
tipo: 'mysql'
servidor: 'localhost'
puerto: '3306'
usuario: 'root'
clave: '12345678'
baseDeDatos: 'vitriappcombd'
...