---
# Base de datos local: 1
# Base de datos externa: 2
identify: 2
...
---
# Para base de datos interna o local: 1
type: 'mysql'
server: 'localhost'
port: '3306'
user: 'root'
password: '12345678'
database: 'vitriappcombd'
...

---
# Para base de datos externa o la del hosting: 2
tipo: 'mysql'
servidor: 'localhost'
puerto: '3306'
usuario: 'u411379380_lamamapollito'
clave: 'QWEQDASDE23423423+-+-+VVsdasdasda123+++'
baseDeDatos: 'u411379380_vitriappcombd'
...